#!/data/data/io.neoterm/files/usr/bin/sh
export CLASSPATH="$(pm path io.neoterm.neotermam 2>&1 </dev/null | cut -d: -f2)"
unset LD_LIBRARY_PATH LD_PRELOAD
exec /system/bin/app_process / io.neoterm.neotermam.Am "$@"
